export const products = [
    {
        id: 0,
        name: 'Цифровая обработка звука',
        tariff: 'бессрочно',
        price: 100000,
        price2: 100,
        avatarSrc: 'https://hholdorf.files.wordpress.com/2015/09/physics-the-nature-of-sound.jpg',
        description: 'Данный продукт представляет собой библиотеку для обработки звуковых файлов.',
        RAM: 2.7,
        cores: 2,
        performance: 2,
        memory: 20,
        keywords: ['Sound', 'Music', 'MP3', 'Voice Recognition'],
        averageRate: 4,
        type: 'библиотека'
    },
    {
        id: 1,
        name: 'Генерация лиц несуществующих людей',
        tariff: 'бессрочно',
        price: 50000,
        price2: 1000,
        avatarSrc: 'https://cameralabs.org/media/lab18/12/21-2/iskusstvennyy-intellekt-sozdaet-portrety-nesuschestvuyuschih-lyudey_4.jpg',
        description: 'Данный продукт представляет собой библиотеку для генерации лиц несуществующих людей в хорошем качестве',
        RAM: 5,
        cores: 1,
        performance: 1,
        memory: 10,
        keywords: ['ML', 'CV', 'Python'],
        averageRate: 4,
        type: 'библиотека'
    },
    {
        id: 2,
        name: 'Мессенджер с высокой степенью шифрования',
        tariff: 'ежедневный',
        price: 5000,
        price2: 200,
        avatarSrc: 'https://www.pngkey.com/png/detail/443-4438515_the-best-ressource-of-free-emoji-png-clipart.png',
        description: 'Это решение представляет собой проект для надежного обмена текстовыми и фаловыми сообщениями.',
        RAM: 1,
        cores: 1,
        performance: 1,
        memory: 2,
        keywords: ['Cryptography', 'Python', 'HTML'],
        averageRate: 5,
        type: 'продукт'
    },
    {
        id: 3,
        name: 'Центральная часть библиотеки для реализации дополненной реальности.',
        tariff: 'бессрочно',
        price: 5000,
        price2: 0,
        avatarSrc: 'https://www.ittechnologynews24.com/wp-content/uploads/2019/07/AR-VR.jpg',
        description: 'С помощью этой библиотеки можно создавать решения в сфере AR',
        RAM: 2.7,
        cores: 4,
        performance: 2,
        memory: 60,
        keywords: ['AI', 'ML', 'CV', 'Python', 'C++'],
        averageRate: 3,
        type: 'библиотека'
    },
    {
        id: 4,
        name: 'Система контроля электроэнергии в доме',
        tariff: 'бессрочно',
        price: 100000,
        price2: 1000,
        avatarSrc: 'https://northcyprussale.ru/uploads/s/d/o/n/don2antj3c4t/img/full_FzgLDdhq.jpg',
        description: 'Здесь реализован функционал для контроля электроэнергии (в том числе домашей) для девайсов Apple Home.',
        RAM: 1,
        cores: 1,
        performance: 1,
        memory: 10,
        keywords: ['Energetics', 'Radiotechnics', 'ML', 'C', 'C++'],
        averageRate: 2,
        type: 'библиотека'
    },
    {
        id: 5,
        name: 'Цифровая обработка звука',
        tariff: 'бессрочно',
        price: 100000,
        price2: 100,
        avatarSrc: 'https://thefinanser.com/wp-content/uploads/2019/10/Product.png',
        description: 'Данный продукт представляет собой библиотеку для обработки звуковых файлов.',
        RAM: 2.7,
        cores: 2,
        performance: 2,
        memory: 20,
        keywords: ['A', 'D', 'C', 'D', 'E', 'R'],
        averageRate: 4,
        type: 'библиотека'
    },
    {
        id: 6,
        name: 'Цифровая обработка звука',
        tariff: 'бессрочно',
        price: 100000,
        price2: 100,
        avatarSrc: 'https://thefinanser.com/wp-content/uploads/2019/10/Product.png',
        description: 'Данный продукт представляет собой библиотеку для обработки звуковых файлов.',
        RAM: 2.7,
        cores: 2,
        performance: 2,
        memory: 20,
        keywords: ['A', 'D', 'C', 'D', 'E', 'R'],
        averageRate: 4,
        type: 'библиотека'
    },
    {
        id: 7,
        name: 'Цифровая обработка звука',
        tariff: 'бессрочно',
        price: 100000,
        price2: 100,
        avatarSrc: 'https://thefinanser.com/wp-content/uploads/2019/10/Product.png',
        description: 'Данный продукт представляет собой библиотеку для обработки звуковых файлов.',
        RAM: 2.7,
        cores: 2,
        performance: 2,
        memory: 20,
        keywords: ['A', 'D', 'C', 'D', 'E', 'R'],
        averageRate: 4,
        type: 'библиотека'
    },
    {
        id: 8,
        name: 'Цифровая обработка звука',
        tariff: 'бессрочно',
        price: 100000,
        price2: 100,
        avatarSrc: 'https://thefinanser.com/wp-content/uploads/2019/10/Product.png',
        description: 'Данный продукт представляет собой библиотеку для обработки звуковых файлов.',
        RAM: 2.7,
        cores: 2,
        performance: 2,
        memory: 20,
        keywords: ['A', 'D', 'C', 'D', 'E', 'R'],
        averageRate: 4,
        type: 'библиотека'
    },
    {
        id: 9,
        name: 'Цифровая обработка звука',
        tariff: 'бессрочно',
        price: 100000,
        price2: 100,
        avatarSrc: 'https://thefinanser.com/wp-content/uploads/2019/10/Product.png',
        description: 'Данный продукт представляет собой библиотеку для обработки звуковых файлов.',
        RAM: 2.7,
        cores: 2,
        performance: 2,
        memory: 20,
        keywords: ['A', 'D', 'C', 'D', 'E', 'R'],
        averageRate: 4,
        type: 'библиотека'
    },
]
